### ISSUE TITLE
Looking for typescript types for this package

### ISSUE THREAD

**Issue by perbergland** [ElasticEmail/elasticemail-js#1]
Are there any type definitions to be found?

**Comment by ReaganM02** [comment]
Any updates on this using typescript? Thank you

**Comment by Abayomzee** [comment]
@perbergland @ReaganM02  check this link out: https://elasticemail.com/developers/api-libraries/typescript-axios

**Comment by ReaganM02** [comment]
Thanks @Abayomzee, I'll check this out 👍
